/**
 * 此文件由 Supabase 自动生成并管理。严禁手动修改、覆盖或重新创建；云服务初始化、关联或恢复时会重新生成此文件。业务代码只能导入和使用本文件导出的内容。
 *
 * This file is automatically generated and managed by Supabase.
 * DO NOT edit, overwrite, or recreate it manually. Only import and use its exports.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// 登录态存储使用动态载体适配器（localStorage / sessionStorage 随「7 天免登录」切换）
import { authStorage } from '@/lib/auth-storage';

declare global {
  interface ImportMetaEnv {
    readonly VITE_SUPABASE_URL?: string;
    readonly VITE_SUPABASE_ANON_KEY?: string;
    readonly VITE_ONEDAY_APP_ID?: string;
    readonly VITE_SUPABASE_AUTH_STORAGE_KEY?: string;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

function requirePublicEnv(value: string | undefined, name: string): string {
  if (!value) {
    throw new Error(`[Supabase] Missing environment variable: ${name}`);
  }
  return value;
}

export const projectUrlId = requirePublicEnv(
  import.meta.env.VITE_ONEDAY_APP_ID,
  'VITE_ONEDAY_APP_ID',
);
export const supabaseUrl = requirePublicEnv(
  import.meta.env.VITE_SUPABASE_URL,
  'VITE_SUPABASE_URL',
);
export const supabaseAnonKey = requirePublicEnv(
  import.meta.env.VITE_SUPABASE_ANON_KEY,
  'VITE_SUPABASE_ANON_KEY',
);
const supabaseAuthStorageKey =
  import.meta.env.VITE_SUPABASE_AUTH_STORAGE_KEY;

export function getSupabaseUrl(): string {
  return supabaseUrl;
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: authStorage,
    ...(supabaseAuthStorageKey
      ? { storageKey: supabaseAuthStorageKey }
      : {}),
  },
  global: {
    headers: { 'OneDay-App-Id': projectUrlId },
  },
});
