// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      ad_campaigns: {
        Row: {
          budget: number | null
          id: string
          name: string
          platform: string | null
          spend: number | null
          status: string | null
          user_id: string | null
        }
        Insert: {
          budget?: number | null
          id?: string
          name: string
          platform?: string | null
          spend?: number | null
          status?: string | null
          user_id?: string | null
        }
        Update: {
          budget?: number | null
          id?: string
          name?: string
          platform?: string | null
          spend?: number | null
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ad_campaigns_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_keywords: {
        Row: {
          campaign: string | null
          clicks: number | null
          id: string
          impressions: number | null
          keyword: string
          status: string | null
          user_id: string | null
        }
        Insert: {
          campaign?: string | null
          clicks?: number | null
          id?: string
          impressions?: number | null
          keyword: string
          status?: string | null
          user_id?: string | null
        }
        Update: {
          campaign?: string | null
          clicks?: number | null
          id?: string
          impressions?: number | null
          keyword?: string
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ad_keywords_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      after_sales: {
        Row: {
          amount: number
          buyer: string
          created_at: string
          id: string
          order_id: string
          product: string
          reason: string
          status: string
          user_id: string | null
        }
        Insert: {
          amount?: number
          buyer?: string
          created_at?: string
          id: string
          order_id?: string
          product?: string
          reason?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          amount?: number
          buyer?: string
          created_at?: string
          id?: string
          order_id?: string
          product?: string
          reason?: string
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "after_sales_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_history: {
        Row: {
          cost: number
          created_at: string
          id: string
          input_text: string
          output_text: string
          service_key: string
          service_name: string
          status: string
          user_id: string | null
        }
        Insert: {
          cost?: number
          created_at?: string
          id?: string
          input_text?: string
          output_text?: string
          service_key?: string
          service_name?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          cost?: number
          created_at?: string
          id?: string
          input_text?: string
          output_text?: string
          service_key?: string
          service_name?: string
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      ai_usage_logs: {
        Row: {
          cost: number
          created_at: string
          id: string
          service_key: string
          service_name: string
          status: string
          user_id: string | null
        }
        Insert: {
          cost?: number
          created_at?: string
          id?: string
          service_key?: string
          service_name?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          cost?: number
          created_at?: string
          id?: string
          service_key?: string
          service_name?: string
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      announcements: {
        Row: {
          content: string | null
          created_at: string | null
          id: string
          status: string | null
          title: string
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          id?: string
          status?: string | null
          title: string
        }
        Update: {
          content?: string | null
          created_at?: string | null
          id?: string
          status?: string | null
          title?: string
        }
        Relationships: []
      }
      email_send_logs: {
        Row: {
          created_at: string
          error: string | null
          fallback: boolean
          id: string
          lang: string
          recipient: string
          render_ok: boolean
          scene: string
          subject: string | null
          success: boolean
        }
        Insert: {
          created_at?: string
          error?: string | null
          fallback?: boolean
          id?: string
          lang?: string
          recipient: string
          render_ok?: boolean
          scene: string
          subject?: string | null
          success?: boolean
        }
        Update: {
          created_at?: string
          error?: string | null
          fallback?: boolean
          id?: string
          lang?: string
          recipient?: string
          render_ok?: boolean
          scene?: string
          subject?: string | null
          success?: boolean
        }
        Relationships: []
      }
      email_templates: {
        Row: {
          body: string
          enabled: boolean
          id: string
          lang: string
          name: string
          scene: string
          subject: string
          updated_at: string
        }
        Insert: {
          body: string
          enabled?: boolean
          id?: string
          lang?: string
          name: string
          scene: string
          subject: string
          updated_at?: string
        }
        Update: {
          body?: string
          enabled?: boolean
          id?: string
          lang?: string
          name?: string
          scene?: string
          subject?: string
          updated_at?: string
        }
        Relationships: []
      }
      bills: {
        Row: {
          amount: number | null
          bill_no: string
          created_at: string | null
          id: string
          status: string | null
          type: string | null
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          bill_no: string
          created_at?: string | null
          id?: string
          status?: string | null
          type?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          bill_no?: string
          created_at?: string | null
          id?: string
          status?: string | null
          type?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bills_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      collect_items: {
        Row: {
          brand: string | null
          category: string | null
          claimed_at: string | null
          claimed_shop: string | null
          created_at: string
          currency: string | null
          description: string | null
          detail_images: Json | null
          error_message: string | null
          id: string
          image: string | null
          images: Json | null
          name: string
          original_price: number | null
          platform: string | null
          price: number | null
          rating: number | null
          raw: Json | null
          reviews: number | null
          sales: number | null
          seller: string | null
          sku: string | null
          source: string | null
          status: string | null
          stock: number | null
          user_id: string | null
          variants: Json | null
        }
        Insert: {
          brand?: string | null
          category?: string | null
          claimed_at?: string | null
          claimed_shop?: string | null
          created_at?: string
          currency?: string | null
          description?: string | null
          detail_images?: Json | null
          error_message?: string | null
          id?: string
          image?: string | null
          images?: Json | null
          name: string
          original_price?: number | null
          platform?: string | null
          price?: number | null
          rating?: number | null
          raw?: Json | null
          reviews?: number | null
          sales?: number | null
          seller?: string | null
          sku?: string | null
          source?: string | null
          status?: string | null
          stock?: number | null
          user_id?: string | null
          variants?: Json | null
        }
        Update: {
          brand?: string | null
          category?: string | null
          claimed_at?: string | null
          claimed_shop?: string | null
          created_at?: string
          currency?: string | null
          description?: string | null
          detail_images?: Json | null
          error_message?: string | null
          id?: string
          image?: string | null
          images?: Json | null
          name?: string
          original_price?: number | null
          platform?: string | null
          price?: number | null
          rating?: number | null
          raw?: Json | null
          reviews?: number | null
          sales?: number | null
          seller?: string | null
          sku?: string | null
          source?: string | null
          status?: string | null
          stock?: number | null
          user_id?: string | null
          variants?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "collect_items_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      collect_settings: {
        Row: {
          auto_claim_shop: string
          banned_words: string
          default_stock: number
          id: string
          price_ending: string
          price_fixed_fee: number
          price_markup: number
          updated_at: string
          user_id: string
        }
        Insert: {
          auto_claim_shop?: string
          banned_words?: string
          default_stock?: number
          id?: string
          price_ending?: string
          price_fixed_fee?: number
          price_markup?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          auto_claim_shop?: string
          banned_words?: string
          default_stock?: number
          id?: string
          price_ending?: string
          price_fixed_fee?: number
          price_markup?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "collect_settings_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      competitor_tracks: {
        Row: {
          created_at: string
          id: string
          name: string
          platform: string | null
          price: number | null
          sales: number | null
          status: string | null
          url: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          platform?: string | null
          price?: number | null
          sales?: number | null
          status?: string | null
          url?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          platform?: string | null
          price?: number | null
          sales?: number | null
          status?: string | null
          url?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "competitor_tracks_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      country_tax_rates: {
        Row: {
          country_code: string
          country_name: string
          created_at: string
          duty_rate: number
          id: string
          note: string | null
          sort_order: number
          tax_free_threshold: number | null
          user_id: string | null
          vat_rate: number
        }
        Insert: {
          country_code: string
          country_name: string
          created_at?: string
          duty_rate?: number
          id?: string
          note?: string | null
          sort_order?: number
          tax_free_threshold?: number | null
          user_id?: string | null
          vat_rate?: number
        }
        Update: {
          country_code?: string
          country_name?: string
          created_at?: string
          duty_rate?: number
          id?: string
          note?: string | null
          sort_order?: number
          tax_free_threshold?: number | null
          user_id?: string | null
          vat_rate?: number
        }
        Relationships: [
          {
            foreignKeyName: "country_tax_rates_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      fba_fee_tiers: {
        Row: {
          created_at: string
          delivery_fee: number
          id: string
          max_dimension: number
          max_weight: number
          sort_order: number
          storage_rate: number
          tier_key: string
          tier_label: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          delivery_fee: number
          id?: string
          max_dimension: number
          max_weight: number
          sort_order?: number
          storage_rate?: number
          tier_key: string
          tier_label: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          delivery_fee?: number
          id?: string
          max_dimension?: number
          max_weight?: number
          sort_order?: number
          storage_rate?: number
          tier_key?: string
          tier_label?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fba_fee_tiers_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      fees: {
        Row: {
          amount: number | null
          category: string | null
          created_at: string | null
          id: string
          name: string
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          category?: string | null
          created_at?: string | null
          id?: string
          name: string
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          category?: string | null
          created_at?: string | null
          id?: string
          name?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fees_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      freight_forwarders: {
        Row: {
          channel: string | null
          id: string
          name: string
          region: string | null
          status: string | null
          user_id: string | null
        }
        Insert: {
          channel?: string | null
          id?: string
          name: string
          region?: string | null
          status?: string | null
          user_id?: string | null
        }
        Update: {
          channel?: string | null
          id?: string
          name?: string
          region?: string | null
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "freight_forwarders_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      fulfillment_plans: {
        Row: {
          id: string
          product: string | null
          qty: number | null
          sku: string
          status: string | null
          user_id: string | null
          warehouse: string | null
        }
        Insert: {
          id?: string
          product?: string | null
          qty?: number | null
          sku: string
          status?: string | null
          user_id?: string | null
          warehouse?: string | null
        }
        Update: {
          id?: string
          product?: string | null
          qty?: number | null
          sku?: string
          status?: string | null
          user_id?: string | null
          warehouse?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fulfillment_plans_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      inbound_orders: {
        Row: {
          created_at: string | null
          id: string
          order_no: string
          qty: number | null
          sku: string | null
          status: string | null
          user_id: string | null
          warehouse: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          order_no: string
          qty?: number | null
          sku?: string | null
          status?: string | null
          user_id?: string | null
          warehouse?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          order_no?: string
          qty?: number | null
          sku?: string | null
          status?: string | null
          user_id?: string | null
          warehouse?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inbound_orders_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory: {
        Row: {
          available: number
          id: string
          in_transit: number
          locked: number
          name: string
          safety_stock: number
          sku: string
          status: string
          updated_at: string
          user_id: string | null
          warehouse: string
        }
        Insert: {
          available?: number
          id: string
          in_transit?: number
          locked?: number
          name: string
          safety_stock?: number
          sku: string
          status?: string
          updated_at?: string
          user_id?: string | null
          warehouse?: string
        }
        Update: {
          available?: number
          id?: string
          in_transit?: number
          locked?: number
          name?: string
          safety_stock?: number
          sku?: string
          status?: string
          updated_at?: string
          user_id?: string | null
          warehouse?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_tasks: {
        Row: {
          created_at: string
          id: string
          product: string
          source: string
          status: string
          target_platforms: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          product?: string
          source?: string
          status?: string
          target_platforms?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          product?: string
          source?: string
          status?: string
          target_platforms?: string
          user_id?: string | null
        }
        Relationships: []
      }
      logistics_channels: {
        Row: {
          carrier: string | null
          days: string | null
          id: string
          name: string
          status: string | null
          user_id: string | null
        }
        Insert: {
          carrier?: string | null
          days?: string | null
          id?: string
          name: string
          status?: string | null
          user_id?: string | null
        }
        Update: {
          carrier?: string | null
          days?: string | null
          id?: string
          name?: string
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "logistics_channels_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      materials: {
        Row: {
          created_at: string | null
          id: string
          name: string
          size: string | null
          type: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          name: string
          size?: string | null
          type?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          size?: string | null
          type?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "materials_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          content: string
          created_at: string
          id: string
          is_read: boolean
          title: string
          type: string
          user_id: string | null
        }
        Insert: {
          content?: string
          created_at?: string
          id?: string
          is_read?: boolean
          title?: string
          type?: string
          user_id?: string | null
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          is_read?: boolean
          title?: string
          type?: string
          user_id?: string | null
        }
        Relationships: []
      }
      operation_logs: {
        Row: {
          action: string
          created_at: string | null
          detail: string | null
          id: string
          module: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string | null
          detail?: string | null
          id?: string
          module?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string | null
          detail?: string | null
          id?: string
          module?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      order_rules: {
        Row: {
          action: string | null
          condition: string | null
          id: string
          name: string
          status: string | null
          user_id: string | null
        }
        Insert: {
          action?: string | null
          condition?: string | null
          id?: string
          name: string
          status?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string | null
          condition?: string | null
          id?: string
          name?: string
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_rules_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          address: string | null
          amount: number
          buyer: string
          channel: string
          created_at: string
          currency: string
          id: string
          product: string
          sku: string
          status: string
          user_id: string | null
        }
        Insert: {
          address?: string | null
          amount?: number
          buyer?: string
          channel?: string
          created_at?: string
          currency?: string
          id: string
          product?: string
          sku?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          address?: string | null
          amount?: number
          buyer?: string
          channel?: string
          created_at?: string
          currency?: string
          id?: string
          product?: string
          sku?: string
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      outbound_orders: {
        Row: {
          created_at: string | null
          id: string
          order_no: string
          qty: number | null
          sku: string | null
          status: string | null
          user_id: string | null
          warehouse: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          order_no: string
          qty?: number | null
          sku?: string | null
          status?: string | null
          user_id?: string | null
          warehouse?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          order_no?: string
          qty?: number | null
          sku?: string | null
          status?: string | null
          user_id?: string | null
          warehouse?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "outbound_orders_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_orders: {
        Row: {
          amount: number
          created_at: string
          id: string
          order_no: string
          paid_at: string | null
          pay_type: string
          plan_id: string | null
          status: string
          user_id: string | null
          wechat_trade_no: string | null
        }
        Insert: {
          amount?: number
          created_at?: string
          id?: string
          order_no: string
          paid_at?: string | null
          pay_type?: string
          plan_id?: string | null
          status?: string
          user_id?: string | null
          wechat_trade_no?: string | null
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          order_no?: string
          paid_at?: string | null
          pay_type?: string
          plan_id?: string | null
          status?: string
          user_id?: string | null
          wechat_trade_no?: string | null
        }
        Relationships: []
      }
      platform_configs: {
        Row: {
          api_key: string | null
          created_at: string | null
          id: string
          name: string
          status: string | null
          type: string | null
        }
        Insert: {
          api_key?: string | null
          created_at?: string | null
          id?: string
          name: string
          status?: string | null
          type?: string | null
        }
        Update: {
          api_key?: string | null
          created_at?: string | null
          id?: string
          name?: string
          status?: string | null
          type?: string | null
        }
        Relationships: []
      }
      products: {
        Row: {
          category: string
          created_at: string
          description: string | null
          id: string
          image: string
          name: string
          price: number
          sales: number
          sku: string
          status: string
          stock: number
          user_id: string | null
          variants: Json | null
        }
        Insert: {
          category?: string
          created_at?: string
          description?: string | null
          id: string
          image?: string
          name: string
          price?: number
          sales?: number
          sku: string
          status?: string
          stock?: number
          user_id?: string | null
          variants?: Json | null
        }
        Update: {
          category?: string
          created_at?: string
          description?: string | null
          id?: string
          image?: string
          name?: string
          price?: number
          sales?: number
          sku?: string
          status?: string
          stock?: number
          user_id?: string | null
          variants?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "products_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          id: string
          role: string | null
          status: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          id: string
          role?: string | null
          status?: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          role?: string | null
          status?: string
          username?: string
        }
        Relationships: []
      }
      profit_records: {
        Row: {
          ad_fee: number
          channel: string
          cost: number
          created_at: string
          id: string
          margin: number
          order_id: string
          platform_fee: number
          product: string
          profit: number
          revenue: number
          shipping: number
          user_id: string | null
        }
        Insert: {
          ad_fee?: number
          channel?: string
          cost?: number
          created_at?: string
          id?: string
          margin?: number
          order_id?: string
          platform_fee?: number
          product?: string
          profit?: number
          revenue?: number
          shipping?: number
          user_id?: string | null
        }
        Update: {
          ad_fee?: number
          channel?: string
          cost?: number
          created_at?: string
          id?: string
          margin?: number
          order_id?: string
          platform_fee?: number
          product?: string
          profit?: number
          revenue?: number
          shipping?: number
          user_id?: string | null
        }
        Relationships: []
      }
      purchase_plans: {
        Row: {
          id: string
          product: string | null
          qty: number | null
          sku: string
          status: string | null
          supplier: string | null
          user_id: string | null
        }
        Insert: {
          id?: string
          product?: string | null
          qty?: number | null
          sku: string
          status?: string | null
          supplier?: string | null
          user_id?: string | null
        }
        Update: {
          id?: string
          product?: string | null
          qty?: number | null
          sku?: string
          status?: string | null
          supplier?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_plans_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_suggestions: {
        Row: {
          available: number
          created_at: string
          daily_sales: number
          id: string
          level: string
          name: string
          safety_stock: number
          sku: string
          suggest_qty: number
          user_id: string | null
        }
        Insert: {
          available?: number
          created_at?: string
          daily_sales?: number
          id: string
          level?: string
          name: string
          safety_stock?: number
          sku: string
          suggest_qty?: number
          user_id?: string | null
        }
        Update: {
          available?: number
          created_at?: string
          daily_sales?: number
          id?: string
          level?: string
          name?: string
          safety_stock?: number
          sku?: string
          suggest_qty?: number
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "purchase_suggestions_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quota_recharges: {
        Row: {
          amount: number
          created_at: string
          id: string
          method: string
          user_id: string | null
        }
        Insert: {
          amount?: number
          created_at?: string
          id?: string
          method?: string
          user_id?: string | null
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          method?: string
          user_id?: string | null
        }
        Relationships: []
      }
      reconciliations: {
        Row: {
          amount: number | null
          bill_no: string
          created_at: string | null
          id: string
          status: string | null
          user_id: string | null
        }
        Insert: {
          amount?: number | null
          bill_no: string
          created_at?: string | null
          id?: string
          status?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number | null
          bill_no?: string
          created_at?: string | null
          id?: string
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reconciliations_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      service_pricing: {
        Row: {
          created_at: string | null
          id: string
          model: string | null
          service_key: string
          service_name: string
          status: string | null
          unit: string | null
          unit_price: number | null
          billing_mode: string | null
          input_price_per_mtok: number | null
          output_price_per_mtok: number | null
          price_tiers: Json | null
          source_url: string | null
          updated_at: string | null
          markup: number | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          model?: string | null
          service_key?: string
          service_name: string
          status?: string | null
          unit?: string | null
          unit_price?: number | null
          billing_mode?: string | null
          input_price_per_mtok?: number | null
          output_price_per_mtok?: number | null
          price_tiers?: Json | null
          source_url?: string | null
          updated_at?: string | null
          markup?: number | null
        }
        Update: {
          created_at?: string | null
          id?: string
          model?: string | null
          service_key?: string
          service_name?: string
          status?: string | null
          unit?: string | null
          unit_price?: number | null
          billing_mode?: string | null
          input_price_per_mtok?: number | null
          output_price_per_mtok?: number | null
          price_tiers?: Json | null
          source_url?: string | null
          updated_at?: string | null
          markup?: number | null
        }
        Relationships: []
      }
      shipments: {
        Row: {
          carrier: string | null
          created_at: string | null
          destination: string | null
          id: string
          origin: string | null
          status: string | null
          tracking_events: Json | null
          tracking_no: string
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          carrier?: string | null
          created_at?: string | null
          destination?: string | null
          id?: string
          origin?: string | null
          status?: string | null
          tracking_events?: Json | null
          tracking_no: string
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          carrier?: string | null
          created_at?: string | null
          destination?: string | null
          id?: string
          origin?: string | null
          status?: string | null
          tracking_events?: Json | null
          tracking_no?: string
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "shipments_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      shipping_quotes: {
        Row: {
          carrier: string
          channel: string
          created_at: string
          currency: string
          days: string
          features: string
          id: string
          price: number
          recommended: boolean
          user_id: string | null
        }
        Insert: {
          carrier?: string
          channel?: string
          created_at?: string
          currency?: string
          days?: string
          features?: string
          id?: string
          price?: number
          recommended?: boolean
          user_id?: string | null
        }
        Update: {
          carrier?: string
          channel?: string
          created_at?: string
          currency?: string
          days?: string
          features?: string
          id?: string
          price?: number
          recommended?: boolean
          user_id?: string | null
        }
        Relationships: []
      }
      shop_auths: {
        Row: {
          access_token: string | null
          authorized_at: string | null
          id: string
          platform: string
          refresh_token: string | null
          region: string | null
          scope: string | null
          shop_domain: string | null
          shop_name: string
          status: string | null
          token_expires_at: string | null
          user_id: string | null
        }
        Insert: {
          access_token?: string | null
          authorized_at?: string | null
          id?: string
          platform: string
          refresh_token?: string | null
          region?: string | null
          scope?: string | null
          shop_domain?: string | null
          shop_name: string
          status?: string | null
          token_expires_at?: string | null
          user_id?: string | null
        }
        Update: {
          access_token?: string | null
          authorized_at?: string | null
          id?: string
          platform?: string
          refresh_token?: string | null
          region?: string | null
          scope?: string | null
          shop_domain?: string | null
          shop_name?: string
          status?: string | null
          token_expires_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "shop_auths_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      shops: {
        Row: {
          created_at: string
          id: string
          name: string
          platform: string
          product_count: number
          rating: number
          region: string
          status: string
          today_orders: number
          today_sales: number
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id: string
          name: string
          platform?: string
          product_count?: number
          rating?: number
          region?: string
          status?: string
          today_orders?: number
          today_sales?: number
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          platform?: string
          product_count?: number
          rating?: number
          region?: string
          status?: string
          today_orders?: number
          today_sales?: number
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "shops_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      sms_codes: {
        Row: {
          code: string
          created_at: string
          expires_at: string
          id: string
          phone: string
          used: boolean
        }
        Insert: {
          code: string
          created_at?: string
          expires_at: string
          id?: string
          phone: string
          used?: boolean
        }
        Update: {
          code?: string
          created_at?: string
          expires_at?: string
          id?: string
          phone?: string
          used?: boolean
        }
        Relationships: []
      }
      source_auths: {
        Row: {
          authorized_at: string | null
          id: string
          platform: string
          source_name: string
          status: string | null
          user_id: string | null
        }
        Insert: {
          authorized_at?: string | null
          id?: string
          platform: string
          source_name: string
          status?: string | null
          user_id?: string | null
        }
        Update: {
          authorized_at?: string | null
          id?: string
          platform?: string
          source_name?: string
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "source_auths_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      sub_accounts: {
        Row: {
          created_at: string
          email: string
          id: string
          name: string
          role: string
          status: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          email?: string
          id?: string
          name?: string
          role?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          name?: string
          role?: string
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      subscription_plans: {
        Row: {
          created_at: string
          description: string | null
          features: Json
          id: string
          name: string
          period: string
          plan_key: string
          price: number
          quota: number
          sort_order: number
          status: string
          max_shops: number | null
          max_products: number | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          features?: Json
          id?: string
          name: string
          period?: string
          plan_key: string
          price?: number
          quota?: number
          sort_order?: number
          status?: string
          max_shops?: number | null
          max_products?: number | null
        }
        Update: {
          created_at?: string
          description?: string | null
          features?: Json
          id?: string
          name?: string
          period?: string
          plan_key?: string
          price?: number
          quota?: number
          sort_order?: number
          status?: string
          max_shops?: number | null
          max_products?: number | null
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          amount: number
          created_at: string
          expires_at: string | null
          id: string
          plan_id: string | null
          plan_name: string
          started_at: string | null
          status: string
          user_id: string | null
        }
        Insert: {
          amount?: number
          created_at?: string
          expires_at?: string | null
          id?: string
          plan_id?: string | null
          plan_name?: string
          started_at?: string | null
          status?: string
          user_id?: string | null
        }
        Update: {
          amount?: number
          created_at?: string
          expires_at?: string | null
          id?: string
          plan_id?: string | null
          plan_name?: string
          started_at?: string | null
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            referencedRelation: "subscription_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      suppliers: {
        Row: {
          contact: string | null
          id: string
          name: string
          phone: string | null
          status: string | null
          user_id: string | null
        }
        Insert: {
          contact?: string | null
          id?: string
          name: string
          phone?: string | null
          status?: string | null
          user_id?: string | null
        }
        Update: {
          contact?: string | null
          id?: string
          name?: string
          phone?: string | null
          status?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "suppliers_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_quotas: {
        Row: {
          balance: number
          id: string
          plan_expires_at: string | null
          plan_id: string | null
          plan_name: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          balance?: number
          id?: string
          plan_expires_at?: string | null
          plan_id?: string | null
          plan_name?: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          balance?: number
          id?: string
          plan_expires_at?: string | null
          plan_id?: string | null
          plan_name?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: []
      }
      traffic_stats: {
        Row: {
          channel: string
          conversion: number | null
          id: string
          orders: number | null
          user_id: string | null
          visits: number | null
        }
        Insert: {
          channel: string
          conversion?: number | null
          id?: string
          orders?: number | null
          user_id?: string | null
          visits?: number | null
        }
        Update: {
          channel?: string
          conversion?: number | null
          id?: string
          orders?: number | null
          user_id?: string | null
          visits?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "traffic_stats_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      has_role: {
        Args: { _user_id: string; _role: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
