-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 为扩展业务表启用 RLS 并添加多租户隔离策略
-- 每张表：users_select_* / users_insert_* / users_update_* / users_delete_*

ALTER TABLE public.shop_auths ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.source_auths ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collect_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fulfillment_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.freight_forwarders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logistics_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.traffic_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_shop_auths ON public.shop_auths FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_shop_auths ON public.shop_auths FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_shop_auths ON public.shop_auths FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_shop_auths ON public.shop_auths FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_source_auths ON public.source_auths FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_source_auths ON public.source_auths FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_source_auths ON public.source_auths FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_source_auths ON public.source_auths FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_collect_items ON public.collect_items FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_collect_items ON public.collect_items FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_collect_items ON public.collect_items FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_collect_items ON public.collect_items FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_materials ON public.materials FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_materials ON public.materials FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_materials ON public.materials FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_materials ON public.materials FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_order_rules ON public.order_rules FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_order_rules ON public.order_rules FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_order_rules ON public.order_rules FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_order_rules ON public.order_rules FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_fulfillment_plans ON public.fulfillment_plans FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_fulfillment_plans ON public.fulfillment_plans FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_fulfillment_plans ON public.fulfillment_plans FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_fulfillment_plans ON public.fulfillment_plans FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_outbound_orders ON public.outbound_orders FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_outbound_orders ON public.outbound_orders FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_outbound_orders ON public.outbound_orders FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_outbound_orders ON public.outbound_orders FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_suppliers ON public.suppliers FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_suppliers ON public.suppliers FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_suppliers ON public.suppliers FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_suppliers ON public.suppliers FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_purchase_plans ON public.purchase_plans FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_purchase_plans ON public.purchase_plans FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_purchase_plans ON public.purchase_plans FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_purchase_plans ON public.purchase_plans FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_inbound_orders ON public.inbound_orders FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_inbound_orders ON public.inbound_orders FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_inbound_orders ON public.inbound_orders FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_inbound_orders ON public.inbound_orders FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_freight_forwarders ON public.freight_forwarders FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_freight_forwarders ON public.freight_forwarders FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_freight_forwarders ON public.freight_forwarders FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_freight_forwarders ON public.freight_forwarders FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_logistics_channels ON public.logistics_channels FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_logistics_channels ON public.logistics_channels FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_logistics_channels ON public.logistics_channels FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_logistics_channels ON public.logistics_channels FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_shipments ON public.shipments FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_shipments ON public.shipments FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_shipments ON public.shipments FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_shipments ON public.shipments FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_ad_campaigns ON public.ad_campaigns FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_ad_campaigns ON public.ad_campaigns FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_ad_campaigns ON public.ad_campaigns FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_ad_campaigns ON public.ad_campaigns FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_ad_keywords ON public.ad_keywords FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_ad_keywords ON public.ad_keywords FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_ad_keywords ON public.ad_keywords FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_ad_keywords ON public.ad_keywords FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_bills ON public.bills FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_bills ON public.bills FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_bills ON public.bills FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_bills ON public.bills FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_fees ON public.fees FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_fees ON public.fees FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_fees ON public.fees FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_fees ON public.fees FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_reconciliations ON public.reconciliations FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_reconciliations ON public.reconciliations FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_reconciliations ON public.reconciliations FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_reconciliations ON public.reconciliations FOR DELETE USING (user_id = auth.uid());

CREATE POLICY users_select_traffic_stats ON public.traffic_stats FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_traffic_stats ON public.traffic_stats FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_traffic_stats ON public.traffic_stats FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_traffic_stats ON public.traffic_stats FOR DELETE USING (user_id = auth.uid());
