-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.inbound_orders ADD COLUMN IF NOT EXISTS sku TEXT; ALTER TABLE public.inbound_orders ADD COLUMN IF NOT EXISTS qty INTEGER DEFAULT 0; ALTER TABLE public.outbound_orders ADD COLUMN IF NOT EXISTS sku TEXT; ALTER TABLE public.outbound_orders ADD COLUMN IF NOT EXISTS qty INTEGER DEFAULT 0;
