-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.after_sales ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_products ON public.products FOR SELECT USING (true);
CREATE POLICY anon_insert_products ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_products ON public.products FOR UPDATE USING (true);
CREATE POLICY anon_delete_products ON public.products FOR DELETE USING (true);

CREATE POLICY anon_select_orders ON public.orders FOR SELECT USING (true);
CREATE POLICY anon_insert_orders ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_orders ON public.orders FOR UPDATE USING (true);
CREATE POLICY anon_delete_orders ON public.orders FOR DELETE USING (true);

CREATE POLICY anon_select_inventory ON public.inventory FOR SELECT USING (true);
CREATE POLICY anon_insert_inventory ON public.inventory FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_inventory ON public.inventory FOR UPDATE USING (true);
CREATE POLICY anon_delete_inventory ON public.inventory FOR DELETE USING (true);

CREATE POLICY anon_select_shops ON public.shops FOR SELECT USING (true);
CREATE POLICY anon_insert_shops ON public.shops FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_shops ON public.shops FOR UPDATE USING (true);
CREATE POLICY anon_delete_shops ON public.shops FOR DELETE USING (true);

CREATE POLICY anon_select_purchase_suggestions ON public.purchase_suggestions FOR SELECT USING (true);
CREATE POLICY anon_insert_purchase_suggestions ON public.purchase_suggestions FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_purchase_suggestions ON public.purchase_suggestions FOR UPDATE USING (true);
CREATE POLICY anon_delete_purchase_suggestions ON public.purchase_suggestions FOR DELETE USING (true);

CREATE POLICY anon_select_after_sales ON public.after_sales FOR SELECT USING (true);
CREATE POLICY anon_insert_after_sales ON public.after_sales FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_after_sales ON public.after_sales FOR UPDATE USING (true);
CREATE POLICY anon_delete_after_sales ON public.after_sales FOR DELETE USING (true);
