-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE POLICY authenticated_insert_product_images ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'd1439de1-7fc8-470b-93ba-152887a05385'); CREATE POLICY anon_select_product_images ON storage.objects FOR SELECT TO anon USING (bucket_id = 'd1439de1-7fc8-470b-93ba-152887a05385');
