-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS address TEXT;
