-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 租户端业务表扩展：为占位页实体建表（多租户隔离）
-- 所有表 user_id 关联 profiles，RLS 基于 auth.uid()

-- 1. 店铺授权
CREATE TABLE IF NOT EXISTS public.shop_auths (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  shop_name TEXT NOT NULL,
  platform TEXT NOT NULL,
  region TEXT,
  status TEXT DEFAULT '正常',
  authorized_at TEXT
);

-- 2. 货源授权
CREATE TABLE IF NOT EXISTS public.source_auths (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  source_name TEXT NOT NULL,
  platform TEXT NOT NULL,
  status TEXT DEFAULT '正常',
  authorized_at TEXT
);

-- 3. 采集箱
CREATE TABLE IF NOT EXISTS public.collect_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  source TEXT,
  category TEXT,
  price NUMERIC,
  status TEXT DEFAULT '待采集'
);

-- 4. 素材库
CREATE TABLE IF NOT EXISTS public.materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT,
  size TEXT,
  created_at TEXT
);

-- 5. 审单规则
CREATE TABLE IF NOT EXISTS public.order_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  condition TEXT,
  action TEXT,
  status TEXT DEFAULT '启用'
);

-- 6. 全托管备货
CREATE TABLE IF NOT EXISTS public.fulfillment_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  product TEXT,
  warehouse TEXT,
  qty INTEGER,
  status TEXT DEFAULT '待备货'
);

-- 7. 出库管理
CREATE TABLE IF NOT EXISTS public.outbound_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  order_no TEXT NOT NULL,
  warehouse TEXT,
  status TEXT DEFAULT '待出库',
  created_at TEXT
);

-- 8. 供应商
CREATE TABLE IF NOT EXISTS public.suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  contact TEXT,
  phone TEXT,
  status TEXT DEFAULT '合作中'
);

-- 9. 采购计划
CREATE TABLE IF NOT EXISTS public.purchase_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  product TEXT,
  qty INTEGER,
  supplier TEXT,
  status TEXT DEFAULT '待采购'
);

-- 10. 入库退货
CREATE TABLE IF NOT EXISTS public.inbound_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  order_no TEXT NOT NULL,
  warehouse TEXT,
  status TEXT DEFAULT '待入库',
  created_at TEXT
);

-- 11. 货代列表
CREATE TABLE IF NOT EXISTS public.freight_forwarders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  channel TEXT,
  region TEXT,
  status TEXT DEFAULT '合作中'
);

-- 12. 渠道配置
CREATE TABLE IF NOT EXISTS public.logistics_channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  carrier TEXT,
  days TEXT,
  status TEXT DEFAULT '启用'
);

-- 13. 物流追踪
CREATE TABLE IF NOT EXISTS public.shipments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  tracking_no TEXT NOT NULL,
  carrier TEXT,
  destination TEXT,
  status TEXT DEFAULT '运输中'
);

-- 14. 广告活动
CREATE TABLE IF NOT EXISTS public.ad_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  platform TEXT,
  budget NUMERIC,
  spend NUMERIC,
  status TEXT DEFAULT '投放中'
);

-- 15. 广告关键词
CREATE TABLE IF NOT EXISTS public.ad_keywords (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  campaign TEXT,
  impressions INTEGER,
  clicks INTEGER,
  status TEXT DEFAULT '监控中'
);

-- 16. 账单明细
CREATE TABLE IF NOT EXISTS public.bills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  bill_no TEXT NOT NULL,
  type TEXT,
  amount NUMERIC,
  status TEXT DEFAULT '待支付',
  created_at TEXT
);

-- 17. 费用管理
CREATE TABLE IF NOT EXISTS public.fees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT,
  amount NUMERIC,
  created_at TEXT
);

-- 18. 对账核销
CREATE TABLE IF NOT EXISTS public.reconciliations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  bill_no TEXT NOT NULL,
  amount NUMERIC,
  status TEXT DEFAULT '待核销',
  created_at TEXT
);

-- 19. 流量统计
CREATE TABLE IF NOT EXISTS public.traffic_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  visits INTEGER,
  orders INTEGER,
  conversion NUMERIC
);
