-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 开发者后台 + 角色权限扩展
-- 1. profiles 表加 role 字段（tenant_user / super_admin）
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'tenant_user';

-- 2. 操作日志表（全局日志）
CREATE TABLE IF NOT EXISTS public.operation_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  action TEXT NOT NULL,
  module TEXT,
  detail TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 系统公告表
CREATE TABLE IF NOT EXISTS public.announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT,
  status TEXT DEFAULT '已发布',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 平台对接配置表
CREATE TABLE IF NOT EXISTS public.platform_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  type TEXT,
  api_key TEXT,
  status TEXT DEFAULT '启用',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 增值服务定价表
CREATE TABLE IF NOT EXISTS public.service_pricing (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service_name TEXT NOT NULL,
  model TEXT,
  unit_price NUMERIC DEFAULT 0,
  unit TEXT DEFAULT '次',
  status TEXT DEFAULT '启用',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
