-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 商品表
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '',
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT '在售',
  image TEXT NOT NULL DEFAULT '',
  sales INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 订单表
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  buyer TEXT NOT NULL DEFAULT '',
  product TEXT NOT NULL DEFAULT '',
  sku TEXT NOT NULL DEFAULT '',
  channel TEXT NOT NULL DEFAULT '',
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL DEFAULT '待处理',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 库存表
CREATE TABLE IF NOT EXISTS public.inventory (
  id TEXT PRIMARY KEY,
  sku TEXT NOT NULL,
  name TEXT NOT NULL,
  warehouse TEXT NOT NULL DEFAULT '',
  available INTEGER NOT NULL DEFAULT 0,
  locked INTEGER NOT NULL DEFAULT 0,
  in_transit INTEGER NOT NULL DEFAULT 0,
  safety_stock INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT '正常',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 店铺表
CREATE TABLE IF NOT EXISTS public.shops (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT '',
  region TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '正常',
  today_sales NUMERIC(12,2) NOT NULL DEFAULT 0,
  today_orders INTEGER NOT NULL DEFAULT 0,
  product_count INTEGER NOT NULL DEFAULT 0,
  rating NUMERIC(3,1) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 采购建议表
CREATE TABLE IF NOT EXISTS public.purchase_suggestions (
  id TEXT PRIMARY KEY,
  sku TEXT NOT NULL,
  name TEXT NOT NULL,
  available INTEGER NOT NULL DEFAULT 0,
  safety_stock INTEGER NOT NULL DEFAULT 0,
  daily_sales INTEGER NOT NULL DEFAULT 0,
  suggest_qty INTEGER NOT NULL DEFAULT 0,
  level TEXT NOT NULL DEFAULT '正常',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 售后单表
CREATE TABLE IF NOT EXISTS public.after_sales (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL DEFAULT '',
  buyer TEXT NOT NULL DEFAULT '',
  product TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '待处理',
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
