-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.collect_items ADD COLUMN IF NOT EXISTS image TEXT; ALTER TABLE public.collect_items ADD COLUMN IF NOT EXISTS sku TEXT;
