-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 开发者后台表 RLS 策略
-- 公告：所有登录用户可读，管理员可写
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_select_announcements ON public.announcements FOR SELECT USING (true);
CREATE POLICY users_insert_announcements ON public.announcements FOR INSERT WITH CHECK (true);
CREATE POLICY users_update_announcements ON public.announcements FOR UPDATE USING (true);
CREATE POLICY users_delete_announcements ON public.announcements FOR DELETE USING (true);

-- 操作日志：所有登录用户可读，可写
ALTER TABLE public.operation_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_select_operation_logs ON public.operation_logs FOR SELECT USING (true);
CREATE POLICY users_insert_operation_logs ON public.operation_logs FOR INSERT WITH CHECK (true);

-- 平台配置：可读写
ALTER TABLE public.platform_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_select_platform_configs ON public.platform_configs FOR SELECT USING (true);
CREATE POLICY users_insert_platform_configs ON public.platform_configs FOR INSERT WITH CHECK (true);
CREATE POLICY users_update_platform_configs ON public.platform_configs FOR UPDATE USING (true);
CREATE POLICY users_delete_platform_configs ON public.platform_configs FOR DELETE USING (true);

-- 增值服务定价：可读写
ALTER TABLE public.service_pricing ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_select_service_pricing ON public.service_pricing FOR SELECT USING (true);
CREATE POLICY users_insert_service_pricing ON public.service_pricing FOR INSERT WITH CHECK (true);
CREATE POLICY users_update_service_pricing ON public.service_pricing FOR UPDATE USING (true);
CREATE POLICY users_delete_service_pricing ON public.service_pricing FOR DELETE USING (true);
