-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.shipments ADD COLUMN IF NOT EXISTS tracking_events JSONB DEFAULT '[]'::jsonb; ALTER TABLE public.shipments ADD COLUMN IF NOT EXISTS origin TEXT; ALTER TABLE public.shipments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(); ALTER TABLE public.shipments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
