-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 为业务表添加 user_id 字段（多租户隔离）
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_suggestions ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.after_sales ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;

-- 删除旧的匿名策略，替换为基于 auth.uid() 的用户隔离策略
DROP POLICY IF EXISTS anon_select_products ON public.products;
DROP POLICY IF EXISTS anon_insert_products ON public.products;
DROP POLICY IF EXISTS anon_update_products ON public.products;
DROP POLICY IF EXISTS anon_delete_products ON public.products;

DROP POLICY IF EXISTS anon_select_orders ON public.orders;
DROP POLICY IF EXISTS anon_insert_orders ON public.orders;
DROP POLICY IF EXISTS anon_update_orders ON public.orders;
DROP POLICY IF EXISTS anon_delete_orders ON public.orders;

DROP POLICY IF EXISTS anon_select_inventory ON public.inventory;
DROP POLICY IF EXISTS anon_insert_inventory ON public.inventory;
DROP POLICY IF EXISTS anon_update_inventory ON public.inventory;
DROP POLICY IF EXISTS anon_delete_inventory ON public.inventory;

DROP POLICY IF EXISTS anon_select_shops ON public.shops;
DROP POLICY IF EXISTS anon_insert_shops ON public.shops;
DROP POLICY IF EXISTS anon_update_shops ON public.shops;
DROP POLICY IF EXISTS anon_delete_shops ON public.shops;

DROP POLICY IF EXISTS anon_select_purchase_suggestions ON public.purchase_suggestions;
DROP POLICY IF EXISTS anon_insert_purchase_suggestions ON public.purchase_suggestions;
DROP POLICY IF EXISTS anon_update_purchase_suggestions ON public.purchase_suggestions;
DROP POLICY IF EXISTS anon_delete_purchase_suggestions ON public.purchase_suggestions;

DROP POLICY IF EXISTS anon_select_after_sales ON public.after_sales;
DROP POLICY IF EXISTS anon_insert_after_sales ON public.after_sales;
DROP POLICY IF EXISTS anon_update_after_sales ON public.after_sales;
DROP POLICY IF EXISTS anon_delete_after_sales ON public.after_sales;

-- 商品：用户只能读写自己的数据
CREATE POLICY users_select_products ON public.products FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_products ON public.products FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_products ON public.products FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_products ON public.products FOR DELETE USING (user_id = auth.uid());

-- 订单
CREATE POLICY users_select_orders ON public.orders FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_orders ON public.orders FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_orders ON public.orders FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_orders ON public.orders FOR DELETE USING (user_id = auth.uid());

-- 库存
CREATE POLICY users_select_inventory ON public.inventory FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_inventory ON public.inventory FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_inventory ON public.inventory FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_inventory ON public.inventory FOR DELETE USING (user_id = auth.uid());

-- 店铺
CREATE POLICY users_select_shops ON public.shops FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_shops ON public.shops FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_shops ON public.shops FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_shops ON public.shops FOR DELETE USING (user_id = auth.uid());

-- 采购建议
CREATE POLICY users_select_purchase_suggestions ON public.purchase_suggestions FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_purchase_suggestions ON public.purchase_suggestions FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_purchase_suggestions ON public.purchase_suggestions FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_purchase_suggestions ON public.purchase_suggestions FOR DELETE USING (user_id = auth.uid());

-- 售后单
CREATE POLICY users_select_after_sales ON public.after_sales FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_after_sales ON public.after_sales FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_after_sales ON public.after_sales FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_after_sales ON public.after_sales FOR DELETE USING (user_id = auth.uid());
