import {
  AppstoreOutlined,
  AuditOutlined,
  ShopOutlined,
  TagsOutlined,
  FileTextOutlined,
  ShoppingCartOutlined,
  ToolOutlined,
  TruckOutlined,
  DollarOutlined,
  BarChartOutlined,
  SettingOutlined,
  HomeOutlined,
  BellOutlined,
  ProfileOutlined,
  DatabaseOutlined,
  AppstoreAddOutlined,
  PictureOutlined,
  FolderOpenOutlined,
  CloudDownloadOutlined,
  CloudSyncOutlined,
  ThunderboltOutlined,
  RobotOutlined,
  InboxOutlined,
  EditOutlined,
  SoundOutlined,
  GiftOutlined,
  UnorderedListOutlined,
  TeamOutlined,
  SafetyOutlined,
  GlobalOutlined,
  ApartmentOutlined,
  StockOutlined,
  SwapOutlined,
  ScanOutlined,
  SendOutlined,
  PrinterOutlined,
  CompassOutlined,
  FundOutlined,
  PayCircleOutlined,
  FileSearchOutlined,
  ImportOutlined,
  ExportOutlined,
  WarningOutlined,
  ScheduleOutlined,
  CalculatorOutlined,
  LineChartOutlined,
  UserOutlined,
  ApiOutlined,
  RocketOutlined,
  KeyOutlined,
  CloudUploadOutlined,
  FieldTimeOutlined,
  LinkOutlined,
} from '@ant-design/icons';
import { P } from '../permissions/codes';
import type { ComponentType } from 'react';

// 菜单节点类型
export interface MenuNode {
  key: string;
  path: string;        // 路由路径
  label: string;       // 中文标题
  icon?: ComponentType;
  permission?: string; // 所需权限码, 不填=不限制
  children?: MenuNode[];
}

// 合并所有图标对象, 统一通过 icons[key] 访问
const allIcons = {
  // 一级模块
  workbench: HomeOutlined,
  auth: SafetyOutlined,
  safety: SafetyOutlined,
  product: TagsOutlined,
  order: ShoppingCartOutlined,
  custody: GiftOutlined,
  purchase: ImportOutlined,
  warehouse: InboxOutlined,
  logistics: TruckOutlined,
  ads: SoundOutlined,
  finance: DollarOutlined,
  data: BarChartOutlined,
  system: SettingOutlined,
  // 子级 / 业务图标
  list: UnorderedListOutlined,
  group: TeamOutlined,
  platform: GlobalOutlined,
  log: AuditOutlined,
  api: CloudDownloadOutlined,
  task: ScheduleOutlined,
  sku: TagsOutlined,
  combo: AppstoreAddOutlined,
  map: SwapOutlined,
  collect: CloudDownloadOutlined,
  online: ShopOutlined,
  off: ShopOutlined,
  illegal: WarningOutlined,
  sync: SwapOutlined,
  record: FileTextOutlined,
  template: FileTextOutlined,
  productTemplate: ProfileOutlined,
  image: PictureOutlined,
  file: FolderOpenOutlined,
  setting: ToolOutlined,
  batch: ThunderboltOutlined,
  move: SendOutlined,
  ai: RobotOutlined,
  aiPick: CompassOutlined,
  aiTranslate: GlobalOutlined,
  aiTitle: EditOutlined,
  aiKeyword: FundOutlined,
  orderList: ProfileOutlined,
  orderHandle: AuditOutlined,
  aftersale: SafetyOutlined,
  refund: PayCircleOutlined,
  returnGoods: ExportOutlined,
  dispute: WarningOutlined,
  manual: EditOutlined,
  syncCenter: CloudSyncOutlined,
  bindShop: ApiOutlined,
  rocket: RocketOutlined,
  key: KeyOutlined,
  taskIcon: ScheduleOutlined,
  splitRule: ApartmentOutlined,
  reviewRule: AuditOutlined,
  print: PrinterOutlined,
  blacklist: WarningOutlined,
  batchOp: ThunderboltOutlined,
  prepare: InboxOutlined,
  outbound: ExportOutlined,
  report: LineChartOutlined,
  shopManage: ShopOutlined,
  supplier: TeamOutlined,
  plan: ScheduleOutlined,
  purchaseIn: ImportOutlined,
  purchaseReturn: ExportOutlined,
  source1688: GlobalOutlined,
  reconcile: CalculatorOutlined,
  selfWarehouse: DatabaseOutlined,
  thirdWarehouse: ApartmentOutlined,
  platformBind: GlobalOutlined,
  inventory: StockOutlined,
  inRecord: ImportOutlined,
  outRecord: ExportOutlined,
  transfer: SwapOutlined,
  stocktaking: ScanOutlined,
  warning: WarningOutlined,
  shelf: ApartmentOutlined,
  pda: ScanOutlined,
  package: InboxOutlined,
  stockSync: SwapOutlined,
  channel: SendOutlined,
  freight: TruckOutlined,
  forwarder: TeamOutlined,
  printTpl: FileTextOutlined,
  waybill: PrinterOutlined,
  matchRule: ApartmentOutlined,
  track: CompassOutlined,
  customs: FileSearchOutlined,
  declareTpl: FileTextOutlined,
  declareData: FolderOpenOutlined,
  adsData: BarChartOutlined,
  adsReport: LineChartOutlined,
  adsRecord: FileTextOutlined,
  adsShop: ShopOutlined,
  profit: FundOutlined,
  platformReconcile: CalculatorOutlined,
  feeFlow: PayCircleOutlined,
  rate: GlobalOutlined,
  cost: CalculatorOutlined,
  payback: PayCircleOutlined,
  deduct: PayCircleOutlined,
  overview: AppstoreOutlined,
  productAnalysis: BarChartOutlined,
  shopStat: ShopOutlined,
  sale: LineChartOutlined,
  traffic: FundOutlined,
  profitAnalysis: FundOutlined,
  subAccount: UserOutlined,
  role: TeamOutlined,
  globalParam: ToolOutlined,
  notify: BellOutlined,
  importExport: ImportOutlined,
  dataSync: SwapOutlined,
  opLog: AuditOutlined,
  auditLog: AuditOutlined,
  backup: CloudUploadOutlined,
  scheduler: FieldTimeOutlined,
  webhook: LinkOutlined,
  billing: DollarOutlined,
  packageInfo: GiftOutlined,
  consume: PayCircleOutlined,
  renew: FundOutlined,
  homeOverview: AppstoreOutlined,
  todo: ScheduleOutlined,
  notice: BellOutlined,
  kanban: BarChartOutlined,
  send: SendOutlined,
  truck: TruckOutlined,
  check: AppstoreOutlined,
  cancel: AppstoreOutlined,
  abnormal: WarningOutlined,
};

const icons = allIcons;

export const menuConfig: MenuNode[] = [
  {
    key: 'workbench',
    path: '/workbench',
    label: '工作台',
    icon: icons.workbench,
    permission: P.dashboard.overview,
    children: [
      { key: 'wb-overview', path: '/workbench/overview', label: '首页总览', icon: icons.homeOverview, permission: P.dashboard.overview },
      { key: 'wb-todo', path: '/workbench/todo', label: '待办中心', icon: icons.todo },
      { key: 'wb-notice', path: '/workbench/notice', label: '业务提醒', icon: icons.notice },
      { key: 'wb-kanban', path: '/workbench/kanban', label: '数据看板', icon: icons.kanban, permission: P.data.overview },
    ],
  },
  {
    key: 'auth',
    path: '/auth',
    label: '授权中心',
    icon: icons.auth,
    permission: P.auth.shopList,
    children: [
      { key: 'auth-shop', path: '/auth/shop', label: '店铺列表', icon: icons.list, permission: P.auth.shopList },
      { key: 'auth-group', path: '/auth/group', label: '店铺分组', icon: icons.group, permission: P.auth.shopList },
      { key: 'auth-platform', path: '/auth/platform', label: '平台管理', icon: icons.platform, permission: P.platform.manage },
      { key: 'auth-log', path: '/auth/log', label: '授权日志', icon: icons.log, permission: P.auth.log },
      { key: 'auth-api-log', path: '/auth/api-log', label: '接口同步日志', icon: icons.api, permission: P.auth.log },
      { key: 'auth-task', path: '/auth/task', label: '任务列表', icon: icons.task, permission: P.auth.shopBind },
      { key: 'auth-sync', path: '/auth/sync', label: '平台同步中心', icon: icons.syncCenter, permission: P.auth.shopBind },
      {
        key: 'auth-bind',
        path: '/auth/bind',
        label: '授权新店铺',
        icon: icons.bindShop,
        permission: P.auth.shopBind,
        children: [
          { key: 'auth-oneclick', path: '/auth/oneclick', label: '一键授权 (OAuth)', icon: icons.rocket, permission: P.auth.shopBind },
          { key: 'auth-manual', path: '/auth/manual', label: '手动授权 (凭证)', icon: icons.key, permission: P.auth.shopBind },
        ],
      },
    ],
  },
  {
    key: 'product',
    path: '/product',
    label: '产品管理',
    icon: icons.product,
    permission: P.product.list,
    children: [
      {
        key: 'product-sku',
        path: '/product/sku',
        label: '内部SKU库',
        icon: icons.sku,
        permission: P.product.list,
        children: [
          { key: 'product-sku-list', path: '/product/sku/list', label: 'SKU列表', icon: icons.list, permission: P.product.list },
          { key: 'product-sku-combo', path: '/product/sku/combo', label: 'SKU组合', icon: icons.combo, permission: P.product.update },
          { key: 'product-sku-map', path: '/product/sku/map', label: 'SKU映射', icon: icons.map, permission: P.product.update },
        ],
      },
      { key: 'product-public-collect', path: '/product/public-collect', label: '公用采集箱', icon: icons.collect, permission: P.product.create },
      { key: 'product-platform-collect', path: '/product/platform-collect', label: '平台采集箱', icon: icons.collect, permission: P.product.create },
      {
        key: 'product-online',
        path: '/product/online',
        label: '在线商品管理',
        icon: icons.online,
        permission: P.product.list,
        children: [
          { key: 'product-online-selling', path: '/product/online/selling', label: '在售商品', icon: icons.online, permission: P.product.list },
          { key: 'product-online-off', path: '/product/online/off', label: '下架商品', icon: icons.off, permission: P.product.list },
          { key: 'product-online-illegal', path: '/product/online/illegal', label: '违规商品', icon: icons.illegal, permission: P.product.list },
          { key: 'product-online-sync', path: '/product/online/sync', label: '商品同步记录', icon: icons.sync, permission: P.product.list },
        ],
      },
      { key: 'product-publish', path: '/product/publish', label: '发布记录', icon: icons.record, permission: P.product.publish },
      { key: 'product-price-tpl', path: '/product/price-tpl', label: '定价模板', icon: icons.template, permission: P.product.update },
      { key: 'product-tpl', path: '/product/tpl', label: '产品模板', icon: icons.productTemplate, permission: P.product.list },
      { key: 'product-image', path: '/product/image', label: '图片素材库', icon: icons.image, permission: P.product.list },
      { key: 'product-file', path: '/product/file', label: '文件中心', icon: icons.file, permission: P.product.list },
      { key: 'product-collect-setting', path: '/product/collect-setting', label: '采集设置', icon: icons.setting, permission: P.product.create },
      { key: 'product-batch', path: '/product/batch', label: '批量操作', icon: icons.batch, permission: P.product.update },
      { key: 'product-move', path: '/product/move', label: '商品搬家', icon: icons.move, permission: P.product.publish },
      {
        key: 'product-ai',
        path: '/product/ai',
        label: 'AI工具',
        icon: icons.ai,
        permission: P.product.list,
        children: [
          { key: 'product-ai-pick', path: '/product/ai/pick', label: 'AI选品', icon: icons.aiPick, permission: P.product.list },
          { key: 'product-ai-translate', path: '/product/ai/translate', label: 'AI翻译', icon: icons.aiTranslate, permission: P.product.update },
          { key: 'product-ai-title', path: '/product/ai/title', label: 'AI标题优化', icon: icons.aiTitle, permission: P.product.update },
          { key: 'product-ai-keyword', path: '/product/ai/keyword', label: 'AI关键词挖掘', icon: icons.aiKeyword, permission: P.product.list },
        ],
      },
    ],
  },
  {
    key: 'order',
    path: '/order',
    label: '订单管理',
    icon: icons.order,
    permission: P.order.list,
    children: [
      { key: 'order-list', path: '/order/list', label: '订单列表', icon: icons.orderList, permission: P.order.list },
      {
        key: 'order-handle',
        path: '/order/handle',
        label: '订单处理',
        icon: icons.orderHandle,
        permission: P.order.list,
        children: [
          { key: 'order-handle-pending', path: '/order/handle/pending', label: '待收款', icon: icons.payback, permission: P.order.list },
          { key: 'order-handle-pay', path: '/order/handle/pay', label: '已付款', icon: icons.payback, permission: P.order.list },
          { key: 'order-handle-toship', path: '/order/handle/toship', label: '待出库', icon: icons.send, permission: P.order.ship },
          { key: 'order-handle-ship', path: '/order/handle/ship', label: '待发货', icon: icons.send, permission: P.order.ship },
          { key: 'order-handle-shipped', path: '/order/handle/shipped', label: '已发货', icon: icons.truck, permission: P.order.list },
          { key: 'order-handle-done', path: '/order/handle/done', label: '已完成', icon: icons.check, permission: P.order.list },
          { key: 'order-handle-cancel', path: '/order/handle/cancel', label: '已取消', icon: icons.cancel, permission: P.order.cancel },
          { key: 'order-handle-abnormal', path: '/order/handle/abnormal', label: '异常订单', icon: icons.abnormal, permission: P.order.list },
        ],
      },
      {
        key: 'order-aftersale',
        path: '/order/aftersale',
        label: '售后单',
        icon: icons.aftersale,
        permission: P.order.aftersale,
        children: [
          { key: 'order-aftersale-refund', path: '/order/aftersale/refund', label: '退款单', icon: icons.refund, permission: P.order.refund },
          { key: 'order-aftersale-return', path: '/order/aftersale/return', label: '退货单', icon: icons.returnGoods, permission: P.order.aftersale },
          { key: 'order-aftersale-dispute', path: '/order/aftersale/dispute', label: '纠纷单', icon: icons.dispute, permission: P.order.aftersale },
        ],
      },
      { key: 'order-manual', path: '/order/manual', label: '手工订单', icon: icons.manual, permission: P.order.manualCreate },
      { key: 'order-split', path: '/order/split', label: '分仓规则', icon: icons.splitRule, permission: P.order.ship },
      { key: 'order-review', path: '/order/review', label: '审单规则', icon: icons.reviewRule, permission: P.order.ship },
      { key: 'order-print', path: '/order/print', label: '打印发货', icon: icons.print, permission: P.order.print },
      { key: 'order-blacklist', path: '/order/blacklist', label: '黑名单', icon: icons.blacklist, permission: P.order.list },
      { key: 'order-batch', path: '/order/batch', label: '订单批量操作', icon: icons.batchOp, permission: P.order.ship },
    ],
  },
  {
    key: 'message',
    path: '/message',
    label: '消息中心',
    icon: icons.notify,
    permission: P.order.list,
    children: [
      { key: 'message-all', path: '/message/all', label: '全部消息', icon: icons.list, permission: P.order.list },
      { key: 'message-unread', path: '/message/unread', label: '未读消息', icon: icons.notify, permission: P.order.list },
    ],
  },
  {
    key: 'custody',
    path: '/custody',
    label: '托管管理',
    icon: icons.custody,
    permission: P.order.list,
    children: [
      { key: 'custody-prepare', path: '/custody/prepare', label: '全托管备货', icon: icons.prepare, permission: P.purchase.create },
      { key: 'custody-outbound', path: '/custody/outbound', label: '出库管理', icon: icons.outbound, permission: P.inventory.adjust },
      { key: 'custody-report', path: '/custody/report', label: '托管报表', icon: icons.report, permission: P.data.overview },
      { key: 'custody-shop', path: '/custody/shop', label: '托管店铺管理', icon: icons.shopManage, permission: P.auth.shopList },
    ],
  },
  {
    key: 'purchase',
    path: '/purchase',
    label: '采购管理',
    icon: icons.purchase,
    permission: P.purchase.list,
    children: [
      { key: 'purchase-supplier', path: '/purchase/supplier', label: '供应商管理', icon: icons.supplier, permission: P.supplier.list },
      { key: 'purchase-plan', path: '/purchase/plan', label: '采购计划', icon: icons.plan, permission: P.purchase.create },
      { key: 'purchase-order', path: '/purchase/order', label: '采购单', icon: icons.orderList, permission: P.purchase.list },
      { key: 'purchase-in', path: '/purchase/in', label: '采购入库', icon: icons.purchaseIn, permission: P.inventory.adjust },
      { key: 'purchase-return', path: '/purchase/return', label: '采购退货', icon: icons.purchaseReturn, permission: P.purchase.approve },
      { key: 'purchase-1688', path: '/purchase/1688', label: '1688货源对接', icon: icons.source1688, permission: P.purchase.create },
      { key: 'purchase-reconcile', path: '/purchase/reconcile', label: '采购对账', icon: icons.reconcile, permission: P.finance.reconcile },
    ],
  },
  {
    key: 'warehouse',
    path: '/warehouse',
    label: '仓库管理',
    icon: icons.warehouse,
    permission: P.warehouse.list,
    children: [
      {
        key: 'warehouse-setting',
        path: '/warehouse/setting',
        label: '仓库设置',
        icon: icons.setting,
        permission: P.warehouse.list,
        children: [
          { key: 'warehouse-self', path: '/warehouse/setting/self', label: '自营仓库', icon: icons.selfWarehouse, permission: P.warehouse.create },
          { key: 'warehouse-third', path: '/warehouse/setting/third', label: '第三方仓库', icon: icons.thirdWarehouse, permission: P.warehouse.create },
          { key: 'warehouse-bind', path: '/warehouse/setting/bind', label: '平台仓绑定', icon: icons.platformBind, permission: P.auth.shopBind },
        ],
      },
      { key: 'warehouse-inventory', path: '/warehouse/inventory', label: '库存清单', icon: icons.inventory, permission: P.inventory.list },
      {
        key: 'warehouse-record',
        path: '/warehouse/record',
        label: '出入库记录',
        icon: icons.file,
        permission: P.inventory.list,
        children: [
          { key: 'warehouse-record-in', path: '/warehouse/record/in', label: '入库记录', icon: icons.inRecord, permission: P.inventory.list },
          { key: 'warehouse-record-out', path: '/warehouse/record/out', label: '出库记录', icon: icons.outRecord, permission: P.inventory.list },
          { key: 'warehouse-record-transfer', path: '/warehouse/record/transfer', label: '调拨记录', icon: icons.transfer, permission: P.inventory.transfer },
          { key: 'warehouse-record-stocktaking', path: '/warehouse/record/stocktaking', label: '盘点记录', icon: icons.stocktaking, permission: P.inventory.stocktaking },
        ],
      },
      { key: 'warehouse-transfer', path: '/warehouse/transfer', label: '库存调拨', icon: icons.transfer, permission: P.inventory.transfer },
      { key: 'warehouse-stocktaking', path: '/warehouse/stocktaking', label: '库存盘点', icon: icons.stocktaking, permission: P.inventory.stocktaking },
      { key: 'warehouse-warning', path: '/warehouse/warning', label: '库存预警', icon: icons.warning, permission: P.inventory.list },
      { key: 'warehouse-shelf', path: '/warehouse/shelf', label: '货架库位管理', icon: icons.shelf, permission: P.warehouse.update },
      { key: 'warehouse-pda', path: '/warehouse/pda', label: 'PDA作业', icon: icons.pda, permission: P.inventory.adjust },
      { key: 'warehouse-package', path: '/warehouse/package', label: '包材管理', icon: icons.package, permission: P.warehouse.update },
      { key: 'warehouse-sync', path: '/warehouse/sync', label: '库存同步设置', icon: icons.stockSync, permission: P.warehouse.update },
    ],
  },
  {
    key: 'logistics',
    path: '/logistics',
    label: '物流分拨',
    icon: icons.logistics,
    permission: P.logistics.channel,
    children: [
      { key: 'logistics-channel', path: '/logistics/channel', label: '物流渠道', icon: icons.channel, permission: P.logistics.channel },
      { key: 'logistics-freight', path: '/logistics/freight', label: '运费模板', icon: icons.freight, permission: P.logistics.channel },
      { key: 'logistics-forwarder', path: '/logistics/forwarder', label: '货代管理', icon: icons.forwarder, permission: P.logistics.channel },
      { key: 'logistics-print-tpl', path: '/logistics/print-tpl', label: '打印模板', icon: icons.printTpl, permission: P.logistics.channel },
      { key: 'logistics-waybill', path: '/logistics/waybill', label: '面单打印', icon: icons.waybill, permission: P.order.print },
      { key: 'logistics-match', path: '/logistics/match', label: '物流匹配规则', icon: icons.matchRule, permission: P.logistics.channel },
      { key: 'logistics-track', path: '/logistics/track', label: '物流轨迹查询', icon: icons.track, permission: P.logistics.track },
      {
        key: 'logistics-customs',
        path: '/logistics/customs',
        label: '海关申报',
        icon: icons.customs,
        permission: P.logistics.channel,
        children: [
          { key: 'logistics-customs-tpl', path: '/logistics/customs/tpl', label: '申报模板', icon: icons.declareTpl, permission: P.logistics.channel },
          { key: 'logistics-customs-data', path: '/logistics/customs/data', label: '报关资料管理', icon: icons.declareData, permission: P.logistics.channel },
        ],
      },
    ],
  },
  {
    key: 'ads',
    path: '/ads',
    label: '广告运营',
    icon: icons.ads,
    permission: P.data.overview,
    children: [
      { key: 'ads-data', path: '/ads/data', label: '广告数据', icon: icons.adsData, permission: P.data.overview },
      { key: 'ads-report', path: '/ads/report', label: '广告报表', icon: icons.adsReport, permission: P.data.overview },
      { key: 'ads-record', path: '/ads/record', label: '广告投放记录', icon: icons.adsRecord, permission: P.data.overview },
      { key: 'ads-shop', path: '/ads/shop', label: '店铺活动管理', icon: icons.adsShop, permission: P.auth.shopList },
    ],
  },
  {
    key: 'finance',
    path: '/finance',
    label: '财务管理',
    icon: icons.finance,
    permission: P.finance.profit,
    children: [
      { key: 'finance-profit', path: '/finance/profit', label: '利润报表', icon: icons.profit, permission: P.finance.profit },
      { key: 'finance-platform', path: '/finance/platform', label: '平台对账', icon: icons.platformReconcile, permission: P.finance.reconcile },
      { key: 'finance-fee', path: '/finance/fee', label: '费用流水', icon: icons.feeFlow, permission: P.finance.profit },
      { key: 'finance-rate', path: '/finance/rate', label: '汇率管理', icon: icons.rate, permission: P.system.global },
      { key: 'finance-cost', path: '/finance/cost', label: '成本核算', icon: icons.cost, permission: P.finance.profit },
      { key: 'finance-payback', path: '/finance/payback', label: '回款记录', icon: icons.payback, permission: P.finance.profit },
      { key: 'finance-deduct', path: '/finance/deduct', label: '扣款明细', icon: icons.deduct, permission: P.finance.profit },
      {
        key: 'finance-bookkeeping',
        path: '/finance/bookkeeping',
        label: '财务记账',
        icon: icons.reconcile,
        permission: P.finance.profit,
        children: [
          { key: 'finance-bookkeeping-overview', path: '/finance/bookkeeping/overview', label: '记账总览', icon: icons.kanban, permission: P.finance.profit },
          { key: 'finance-bookkeeping-coa', path: '/finance/bookkeeping/coa', label: '会计科目', icon: icons.list, permission: P.finance.profit },
          { key: 'finance-bookkeeping-voucher', path: '/finance/bookkeeping/voucher', label: '记账凭证', icon: icons.record, permission: P.finance.profit },
          { key: 'finance-bookkeeping-reconcile', path: '/finance/bookkeeping/reconcile', label: '余额对账', icon: icons.platformReconcile, permission: P.finance.reconcile },
          { key: 'finance-bookkeeping-trial', path: '/finance/bookkeeping/trial', label: '科目余额表', icon: icons.report, permission: P.finance.profit },
          { key: 'finance-bookkeeping-income', path: '/finance/bookkeeping/income', label: '利润表', icon: icons.profit, permission: P.finance.profit },
        ],
      },
    ],
  },
  {
    key: 'marketing',
    path: '/marketing',
    label: '营销中心',
    icon: icons.custody,
    permission: P.order.list,
    children: [
      { key: 'marketing-coupons', path: '/marketing/coupons', label: '优惠券', icon: icons.sku, permission: P.order.list },
    ],
  },
  {
    key: 'data',
    path: '/data',
    label: '数据中心',
    icon: icons.data,
    permission: P.data.overview,
    children: [
      { key: 'data-overview', path: '/data/overview', label: '运营总览', icon: icons.overview, permission: P.data.overview },
      { key: 'data-bi', path: '/data/bi', label: 'BI 数据看板', icon: icons.kanban, permission: P.data.overview },
      { key: 'data-product', path: '/data/product', label: '商品数据分析', icon: icons.productAnalysis, permission: P.data.overview },
      { key: 'data-shop', path: '/data/shop', label: '店铺统计', icon: icons.shopStat, permission: P.data.overview },
      { key: 'data-sale', path: '/data/sale', label: '销售报表', icon: icons.sale, permission: P.data.overview },
      { key: 'data-traffic', path: '/data/traffic', label: '流量分析', icon: icons.traffic, permission: P.data.overview },
      { key: 'data-realtime', path: '/data/realtime', label: '实时大屏', icon: icons.kanban, permission: P.data.overview },
      { key: 'data-profit', path: '/data/profit', label: '利润分析', icon: icons.profitAnalysis, permission: P.finance.profit },
    ],
  },
  {
    key: 'system',
    path: '/system',
    label: '系统设置',
    icon: icons.system,
    permission: P.system.subAccount,
    children: [
      { key: 'system-sub', path: '/system/sub', label: '子账号管理', icon: icons.subAccount, permission: P.system.subAccount },
      { key: 'system-role', path: '/system/role', label: '角色权限', icon: icons.role, permission: P.system.role },
      { key: 'system-global', path: '/system/global', label: '全局参数', icon: icons.globalParam, permission: P.system.global },
      { key: 'system-notify', path: '/system/notify', label: '通知设置', icon: icons.notify, permission: P.system.global },
      { key: 'system-import', path: '/system/import', label: '导入导出中心', icon: icons.importExport, permission: P.data.export },
      { key: 'system-sync', path: '/system/sync', label: '数据同步中心', icon: icons.dataSync, permission: P.system.global },
      { key: 'system-op-log', path: '/system/op-log', label: '操作日志', icon: icons.opLog, permission: P.system.opLog },
      { key: 'system-audit-log', path: '/system/audit-log', label: '审计日志', icon: icons.auditLog, permission: P.system.auditLog },
      { key: 'system-backup', path: '/system/backup', label: '数据备份', icon: icons.backup, permission: P.system.global },
      { key: 'system-scheduler', path: '/system/scheduler', label: '定时任务', icon: icons.scheduler, permission: P.system.global },
      { key: 'system-webhook', path: '/system/webhook', label: 'Webhook', icon: icons.webhook, permission: P.system.global },
      { key: 'system-invite', path: '/system/invite', label: '邀请分销', icon: icons.rocket, permission: P.system.global },
      { key: 'system-isolation', path: '/system/isolation', label: '租户隔离', icon: icons.safety, permission: P.system.global },
      { key: 'system-workflow', path: '/system/workflow', label: '审批中心', icon: icons.reviewRule, permission: P.system.global },
      {
        key: 'system-billing',
        path: '/system/billing',
        label: '订阅与账单',
        icon: icons.billing,
        permission: P.system.global,
        children: [
          { key: 'system-billing-plan', path: '/system/billing/plan', label: '套餐信息', icon: icons.packageInfo, permission: P.system.global },
          { key: 'system-billing-consume', path: '/system/billing/consume', label: '消费记录', icon: icons.consume, permission: P.finance.profit },
          { key: 'system-billing-renew', path: '/system/billing/renew', label: '续费升级', icon: icons.renew, permission: P.system.global },
        ],
      },
    ],
  },
];

// 递归拍平所有路径,用于生成路由
// 子节点 path 既支持相对 (如 "list") 也支持绝对 (如 "/order/handle/pay"),
// 规则: 若子 path 以 "/" 开头, 直接使用; 否则拼到父 path 之后
export function flattenPaths(nodes: MenuNode[] = menuConfig, parent = ''): string[] {
  const acc: string[] = [];
  for (const n of nodes) {
    const isAbs = n.path.startsWith('/');
    const p = isAbs ? n.path : (parent ? `${parent}${n.path.startsWith('/') ? '' : '/'}${n.path.replace(/^\//, '')}` : n.path);
    acc.push(p);
    if (n.children) acc.push(...flattenPaths(n.children, p));
  }
  return Array.from(new Set(acc));
}

export const allPaths = flattenPaths();
